#!/bin/bash

# create user 'retex' with no priveleges
useradd retex

# make a chroot jail that can run latex.py
JAIL=/retex-jail
mkdir $JAIL
jk_cp $JAIL /usr/bin/python
jk_cp $JAIL /usr/lib/python*/
jk_cp $JAIL /usr/lib/pymodules/python*/plasTeX/
cp src/latex.py $JAIL/latex.py
chown -R retex:retex $JAIL/*
chmod -R a-w $JAIL
chmod a+rx $JAIL/latex.py
